<?php
/**
 * Created by PhpStorm.
 * User: Zani
 * Date: 04.04.2017
 * Time: 11:32
 */
use Drupal\node\Entity\NodeType;
use \Drupal\Core\Entity\EntityInterface;
use \Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_entity_extra_field_info().
 */
function voting_entity_extra_field_info() {
  $extra = array();

  foreach (NodeType::loadMultiple() as $bundle) {
    $extra['node'][$bundle->Id()]['display']['my_own_pseudo_field'] = array(
      'label' => t('My own field'),
      'description' => t('This is my own pseudo-field'),
      'weight' => 100,
      'visible' => TRUE,
    );
  }

  return $extra;
}



function voting_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {

  // Show form only for /node/{nid} path
  $only_node_route = "entity.node.canonical";
  if(\Drupal::routeMatch()->getRouteName() != $only_node_route){
    return;
  }
  // Hide 'Voting' for Anonymous user
  if(Drupal::currentUser()->isAnonymous()){
    return;
  }
  // Show form if pseudo field is available
  if ($display->getComponent('my_own_pseudo_field')) {

    $build['form'] = \Drupal::formBuilder()->getForm('\Drupal\voting\Form\ZannAjaxFormLike');

   }
}